apiVersion: v1
kind: Service
metadata:
  name: codify-submit
  namespace: codify
spec:
  selector:
    app: codify-submit-label
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: actuator
    port: 9090
    targetPort: 9090
  type: NodePort
