apiVersion: v1
kind: Service
metadata:
  name: codify-gateway-svc
  namespace: codify
spec:
  selector:
    app: codify-gateway-label
  ports:
    - name: http
      port: 80
      targetPort: 8080
   - name: actuator
     port: 9090
     targetPort: 9090
  type: NodePort
